[ids]
*

[main]
capslock = layer(control)
leftalt = leftmeta
leftmeta = overloadt(meta_ctrl, macro(muhenkan f14), 200)
rightmeta = overloadt(right_ctrl, macro(henkan f15), 200)

[meta_ctrl:C]
h = left
j = down
k = up
l = right

[right_ctrl:C]
